apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  annotations:
  argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  project: my-project
  source:
    path: my-apps
    repoURL: https://github.com/hseligson1/app-of-apps
    targetRevision: HEAD
